<?php

namespace App\Http\Livewire;

use Livewire\Component;

class SomeComplexComponent extends Component
{
    public $data = [];

    public function mount()
    {
        $this->data = $this->generateData();
    }

    public function render()
    {
        return view('livewire.some-complex-component', [
            'data' => $this->data
        ]);
    }

    public function doSomething()
    {
        $this->data = $this->generateData();
    }

    private function generateData()
    {
        $dataJson = '{
   "rows":{
      "124":{
         "1":-133,
         "main":85,
         "secondary":0
      },
      "192":{
         "5":0,
         "main":70,
         "secondary":0
      },
      "194":{
         "5":0,
         "main":30,
         "secondary":0
      },
      "195":{
         "5":0,
         "main":70,
         "secondary":0
      },
      "373":{
         "main":143,
         "3":0,
         "5":25,
         "secondary":20
      },
      "517":{
         "3":84,
         "main":56,
         "secondary":26
      },
      "574":{
         "3":0,
         "main":40,
         "secondary":0
      },
      "605":{
         "1":-72,
         "main":48,
         "secondary":0
      },
      "649":{
         "3":-41,
         "main":150,
         "secondary":0
      },
      "650":{
         "1":-63,
         "main":240,
         "secondary":0
      },
      "651":{
         "3":-173,
         "main":136,
         "secondary":13
      },
      "683":{
         "3":0,
         "main":368,
         "secondary":0
      },
      "773":{
         "3":-21,
         "main":0,
         "secondary":0
      },
      "795":{
         "3":4,
         "main":0,
         "secondary":13
      },
      "830":{
         "3":-68,
         "main":0,
         "secondary":28
      },
      "831":{
         "3":28,
         "main":16,
         "secondary":0
      },
      "845":{
         "3":2,
         "main":194,
         "secondary":100
      },
      "906":{
         "3":0,
         "main":350,
         "secondary":0
      },
      "1022":{
         "3":63,
         "main":150,
         "secondary":100
      },
      "1023":{
         "3":-57,
         "main":654,
         "secondary":100
      },
      "1048":{
         "3":130,
         "main":9,
         "secondary":0
      },
      "1049":{
         "3":24,
         "main":0,
         "secondary":0
      },
      "1052":{
         "main":750,
         "3":19,
         "5":0,
         "secondary":0
      },
      "1059":{
         "5":0,
         "main":150,
         "secondary":0
      },
      "1064":{
         "3":-17,
         "main":142,
         "secondary":0
      },
      "1065":{
         "3":83,
         "main":450,
         "secondary":100
      },
      "1068":{
         "3":0,
         "main":105,
         "secondary":0
      },
      "1076":{
         "3":111,
         "main":325,
         "secondary":50
      },
      "1077":{
         "3":0,
         "main":0,
         "secondary":0
      },
      "1078":{
         "5":0,
         "main":0,
         "secondary":0
      },
      "23136":{
         "143":{
            "needed":7
         },
         "426":{
            "needed":5
         },
         "443":{
            "needed":1
         }
      },
      "24931":{
         "500":{
            "needed":13
         },
         "503":{
            "needed":0.5
         },
         "504":{
            "needed":4.5
         },
         "618":{
            "needed":5
         },
         "941":{
            "needed":2
         },
         "942":{
            "needed":2
         },
         "943":{
            "needed":1
         }
      },
      "25416":{
         "330":{
            "needed":4
         },
         "928":{
            "needed":5
         },
         "929":{
            "needed":15
         },
         "931":{
            "needed":7.5
         }
      },
      "25427":{
         "455":{
            "needed":2
         },
         "551":{
            "needed":8
         },
         "1253":{
            "needed":3
         },
         "1254":{
            "needed":11
         },
         "1255":{
            "needed":5.5
         },
         "1256":{
            "needed":5.5
         },
         "1257":{
            "needed":11
         }
      },
      "25451":{
         "330":{
            "needed":4
         },
         "928":{
            "needed":5
         },
         "929":{
            "needed":15
         },
         "931":{
            "needed":7.5
         }
      },
      "25498":{
         "596":{
            "needed":3
         },
         "597":{
            "needed":13
         },
         "598":{
            "needed":8.5
         },
         "811":{
            "needed":7
         },
         "812":{
            "needed":7.5
         },
         "813":{
            "needed":0.5
         },
         "814":{
            "needed":0.5
         },
         "815":{
            "needed":1
         },
         "816":{
            "needed":0.5
         },
         "817":{
            "needed":3
         },
         "818":{
            "needed":3
         }
      },
      "25503":{
         "330":{
            "needed":4
         },
         "928":{
            "needed":5
         },
         "929":{
            "needed":15
         },
         "931":{
            "needed":7.5
         }
      },
      "25974":{
         "216":{
            "needed":8.3
         },
         "219":{
            "needed":6
         },
         "220":{
            "needed":13
         }
      }
   }
}';

        return json_decode($dataJson, true);
    }
}
